In [6]:
from sklearn.impute import SimpleImputer

In [4]:
import pandas as pd

In [5]:
from numpy import array
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [7]:
# example data
data = ['warm', 'hot', 'cold', 'luke warm', 'hot', 'cold', 'warm']

In [8]:
# converting to numeric form for computation
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(data)

In [9]:
integer_encoded

# Output: array([3, 1, 0, 2, 1, 0, 3]), where 3 = warm, 1 = hot, ...

array([3, 1, 0, 2, 1, 0, 3])

In [10]:
inverted = label_encoder.inverse_transform(integer_encoded)[2]
print(inverted)

cold


In [14]:
onehot_encoder = OneHotEncoder(sparse_output=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1) # reshapes array to matrix

In [15]:
integer_encoded

array([[3],
       [1],
       [0],
       [2],
       [1],
       [0],
       [3]])

In [16]:
# Using One Hot encoder
# One hot encoding creates an identity matrix
# One hot encoding - used when encoding independent variables

onehot_encoded = onehot_encoder.fit_transform(integer_encoded)

In [17]:
onehot_encoded

array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [22]:
import numpy as np

In [26]:
# [3, :] - means row number 3, and all columns
# [0, :] - means row number 0, and all columns

inverted = label_encoder.inverse_transform([np.argmax(onehot_encoded[1, :])])

In [27]:
inverted

array(['hot'], dtype='<U9')